Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -17,14 +17,20 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install pylint pulp
+        pip install pylint
     - name: Analysing the code with pylint
       run: |
-        pylint_score=$(pylint --score=y $(git ls-files '*.py') | grep -oP '(?<=Your code has been rated at ).*(?=/10)')
+        set -x
+        
+        pylint_output=$(pylint --score=y --rcfile .pylintrc $(git ls-files '*.py'))
+        pylint_score=$(echo "$pylint_output" | grep -oP '(?<=Your code has been rated at ).*(?=/10)' || true)
+        echo "Pylint Score: $pylint_score"
+        
         if (( $(echo "$pylint_score > 8.5" | bc -l) )); then
-          echo "Проверка прошла успешно!"
+          echo "Check passed successfully!"
         else
-          echo "Пересмотрите код..."
+          echo "Code quality is below standard. Review the errors below:"
+          pylint_errors=$(echo "$pylint_output" | grep -A1 '=== Your code has been rated' || true)
+          echo "$pylint_errors"
+          exit 1
         fi
-        pylint $(git ls-files '*.py')
-  
